import brand1 from "./assets/images/brands/logo-1.png";
import brand2 from "./assets/images/brands/logo-2.png";
import brand3 from "./assets/images/brands/logo-3.png";
import brand4 from "./assets/images/brands/logo-4.png";
import brand5 from "./assets/images/brands/logo-5.png";
import brand6 from "./assets/images/brands/logo-6.png";

export const brands = [
  {
    id: 1,
    name: "BMW",
    image: brand6,
  },
  {
    id: 2,
    name: "Hyundai",
    image: brand5,
  },
  {
    id: 3,
    name: "Mahindra",
    image: brand4,
  },
  {
    id: 4,
    name: "MarutiSuzuki",
    image: brand1,
  },
  {
    id: 5,
    name: "Mercedes-Benz",
    image: brand3,
  },
  {
    id: 6,
    name: "Toyota",
    image: brand2,
  },
];

import BMWLogo from "./assets/images/category/BMW.png";
import HyundaiLogo from "./assets/images/category/Hyundai.png";
import MahindraLogo from "./assets/images/category/Mahindra.png";
import MarutiSuzukiLogo from "./assets/images/category/Maruti-Suzuki.png";
import MercedesBenzLogo from "./assets/images/category/Mercedes-Benz.png";
import ToyotaLogo from "./assets/images/category/Toyota.png";

export const categories = [
  {
    id: 1,
    name: "BMW",
    image: BMWLogo,
  },
  {
    id: 2,
    name: "Hyundai",
    image: HyundaiLogo,
  },
  {
    id: 3,
    name: "Mahindra",
    image: MahindraLogo,
  },
  {
    id: 4,
    name: "MarutiSuzuki",
    image: MarutiSuzukiLogo,
  },
  {
    id: 5,
    name: "MercedesBenz",
    image: MercedesBenzLogo,
  },
  {
    id: 6,
    name: "Toyota",
    image: ToyotaLogo,
  },
];

import BMW1 from "./assets/images/cars/BMW-1.png";
import BMW2 from "./assets/images/cars/BMW-2.png";
import BMW3 from "./assets/images/cars/BMW-3.png";
import BMW4 from "./assets/images/cars/BMW-4.png";
import BMW5 from "./assets/images/cars/BMW-5.png";
import BMW6 from "./assets/images/cars/BMW-6.png";
import BMW7 from "./assets/images/cars/BMW-7.png";
import BMW8 from "./assets/images/cars/BMW-8.png";

export const BMW = [
  {
    id: 1,
    brand: "BMW",
    model: "BMW-X5",
    category: "SUV",
    year: 2022,
    price_per_day: 120,
    availability: true,
    location: "New York",
    transmission: "Automatic",
    fuel_type: "Diesel",
    seating_capacity: 7,
    air_conditioning: true,
    features: ["Bluetooth", "GPS", "Sunroof"],
    image: BMW1,
    rating: 4.8,
    mileage: 15000,
    trending: true,
  },
  {
    id: 2,
    brand: "BMW",
    model: "BMW-3Series",
    category: "Sedan",
    year: 2021,
    price_per_day: 90,
    availability: true,
    location: "Los Angeles",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Heated Seats", "Sunroof"],
    image: BMW2,
    rating: 4.7,
    mileage: 20000,
    trending: false,
  },
  {
    id: 3,
    brand: "BMW",
    model: "BMW-i8",
    category: "Sports",
    year: 2023,
    price_per_day: 250,
    availability: true,
    location: "Miami",
    transmission: "Automatic",
    fuel_type: "Hybrid",
    seating_capacity: 2,
    air_conditioning: true,
    features: ["Bluetooth", "Sports Mode", "Luxury Interior"],
    image: BMW3,
    rating: 4.9,
    mileage: 5000,
    trending: false,
  },
  {
    id: 4,
    brand: "BMW",
    model: "BMW-5Series",
    category: "Luxury",
    year: 2022,
    price_per_day: 150,
    availability: true,
    location: "San Francisco",
    transmission: "Automatic",
    fuel_type: "Diesel",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["GPS", "Panoramic Roof", "Leather Seats"],
    image: BMW4,
    rating: 4.8,
    mileage: 10000,
    trending: false,
  },
  {
    id: 5,
    brand: "BMW",
    model: "BMW-Z4",
    category: "Convertible",
    year: 2021,
    price_per_day: 180,
    availability: true,
    location: "Chicago",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seating_capacity: 2,
    air_conditioning: true,
    features: ["Bluetooth", "Convertible Roof"],
    image: BMW5,
    rating: 4.7,
    mileage: 8000,
    trending: false,
  },
  {
    id: 6,
    brand: "BMW",
    model: "BMW-X3",
    category: "SUV",
    year: 2022,
    price_per_day: 110,
    availability: true,
    location: "Seattle",
    transmission: "Automatic",
    fuel_type: "Diesel",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Bluetooth", "GPS", "Rear Camera"],
    image: BMW6,
    rating: 4.5,
    mileage: 15000,
    trending: false,
  },
  {
    id: 7,
    brand: "BMW",
    model: "BMW-7Series",
    category: "Luxury",
    year: 2023,
    price_per_day: 200,
    availability: true,
    location: "Boston",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Bluetooth", "Massage Seats", "Advanced Safety"],
    image: BMW7,
    rating: 4.9,
    mileage: 5000,
    trending: false,
  },
  {
    id: 8,
    brand: "BMW",
    model: "BMW-M4",
    category: "Sports",
    year: 2023,
    price_per_day: 230,
    availability: true,
    location: "Dallas",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seating_capacity: 4,
    air_conditioning: true,
    features: ["Bluetooth", "Sports Mode", "Luxury Seats"],
    image: BMW8,
    rating: 4.9,
    mileage: 8000,
    trending: false,
  },
];

import Mahindra1 from "./assets/images/cars/Mahindra-1.png";
import Mahindra2 from "./assets/images/cars/Mahindra-2.png";
import Mahindra3 from "./assets/images/cars/Mahindra-3.png";
import Mahindra4 from "./assets/images/cars/Mahindra-4.png";
import Mahindra5 from "./assets/images/cars/Mahindra-5.png";
import Mahindra6 from "./assets/images/cars/Mahindra-6.png";
import Mahindra7 from "./assets/images/cars/Mahindra-7.png";
import Mahindra8 from "./assets/images/cars/Mahindra-8.png";

export const Mahindra = [
  {
    id: 9,
    brand: "Mahindra",
    model: "Mahindra-Thar",
    category: "SUV",
    year: 2022,
    price_per_day: 80,
    availability: true,
    location: "Mumbai",
    transmission: "Manual",
    fuel_type: "Diesel",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Bluetooth", "GPS", "Off-Road Capability"],
    image: Mahindra1,
    rating: 4.8,
    mileage: 15000,
    trending: true,
  },
  {
    id: 10,
    brand: "Mahindra",
    model: "Mahindra-Scorpio",
    category: "SUV",
    year: 2021,
    price_per_day: 75,
    availability: true,
    location: "Delhi",
    transmission: "Manual",
    fuel_type: "Diesel",
    seating_capacity: 7,
    air_conditioning: true,
    features: ["Rear Camera", "Bluetooth", "Spacious Interior"],
    image: Mahindra2,
    rating: 4.5,
    mileage: 20000,
    trending: false,
  },
  {
    id: 11,
    brand: "Mahindra",
    model: "Mahindra-XUV700",
    category: "SUV",
    year: 2023,
    price_per_day: 100,
    availability: true,
    location: "Bangalore",
    transmission: "Automatic",
    fuel_type: "Diesel",
    seating_capacity: 7,
    air_conditioning: true,
    features: ["Panoramic Roof", "Advanced Safety Features"],
    image: Mahindra3,
    rating: 4.9,
    mileage: 8000,
    trending: false,
  },
  {
    id: 12,
    brand: "Mahindra",
    model: "Mahindra-Bolero",
    category: "SUV",
    year: 2020,
    price_per_day: 60,
    availability: true,
    location: "Pune",
    transmission: "Manual",
    fuel_type: "Diesel",
    seating_capacity: 7,
    air_conditioning: true,
    features: ["Durable Build", "Basic Safety Features"],
    image: Mahindra4,
    rating: 4.3,
    mileage: 30000,
    trending: false,
  },
  {
    id: 13,
    brand: "Mahindra",
    model: "Mahindra-Marazzo",
    category: "MPV",
    year: 2021,
    price_per_day: 70,
    availability: true,
    location: "Ahmedabad",
    transmission: "Manual",
    fuel_type: "Diesel",
    seating_capacity: 7,
    air_conditioning: true,
    features: ["Spacious Interior", "Bluetooth", "Rear Camera"],
    image: Mahindra5,
    rating: 4.4,
    mileage: 25000,
    trending: false,
  },
  {
    id: 14,
    brand: "Mahindra",
    model: "Mahindra-KUV100",
    category: "Compact SUV",
    year: 2020,
    price_per_day: 50,
    availability: true,
    location: "Chennai",
    transmission: "Manual",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Fuel Efficiency", "Basic Safety"],
    image: Mahindra6,
    rating: 4.2,
    mileage: 30000,
    trending: false,
  },
  {
    id: 15,
    brand: "Mahindra",
    model: "Mahindra-TUV300",
    category: "SUV",
    year: 2021,
    price_per_day: 65,
    availability: true,
    location: "Kolkata",
    transmission: "Manual",
    fuel_type: "Diesel",
    seating_capacity: 7,
    air_conditioning: true,
    features: ["Durable Build", "Bluetooth"],
    image: Mahindra7,
    rating: 4.3,
    mileage: 20000,
    trending: false,
  },
  {
    id: 16,
    brand: "Mahindra",
    model: "Mahindra-XUV300",
    category: "Compact SUV",
    year: 2022,
    price_per_day: 85,
    availability: true,
    location: "Jaipur",
    transmission: "Automatic",
    fuel_type: "Diesel",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Rear Camera", "Advanced Safety Features"],
    image: Mahindra8,
    rating: 4.6,
    mileage: 12000,
    trending: false,
  },
];

import MarutiSuzuki1 from "./assets/images/cars/Maruti-Suzuki-1.png";
import MarutiSuzuki2 from "./assets/images/cars/Maruti-Suzuki-2.png";
import MarutiSuzuki3 from "./assets/images/cars/Maruti-Suzuki-3.png";
import MarutiSuzuki4 from "./assets/images/cars/Maruti-Suzuki-4.png";
import MarutiSuzuki5 from "./assets/images/cars/Maruti-Suzuki-5.png";
import MarutiSuzuki6 from "./assets/images/cars/Maruti-Suzuki-6.png";
import MarutiSuzuki7 from "./assets/images/cars/Maruti-Suzuki-7.png";
import MarutiSuzuki8 from "./assets/images/cars/Maruti-Suzuki-8.png";

export const MarutiSuzuki = [
  {
    id: 17,
    brand: "MarutiSuzuki",
    model: "Maruti-Swift",
    category: "Hatchback",
    year: 2021,
    price_per_day: 45,
    availability: true,
    location: "Delhi",
    transmission: "Manual",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Fuel Efficiency", "Bluetooth"],
    image: MarutiSuzuki1,
    rating: 4.2,
    mileage: 30000,
    trending: false,
  },
  {
    id: 18,
    brand: "MarutiSuzuki",
    model: "Maruti-Baleno",
    category: "Hatchback",
    year: 2022,
    price_per_day: 50,
    availability: true,
    location: "Mumbai",
    transmission: "Manual",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Rear Camera", "Bluetooth"],
    image: MarutiSuzuki2,
    rating: 4.4,
    mileage: 25000,
    trending: false,
  },
  {
    id: 19,
    brand: "MarutiSuzuki",
    model: "Maruti-WagonR",
    category: "Hatchback",
    year: 2020,
    price_per_day: 40,
    availability: true,
    location: "Bangalore",
    transmission: "Manual",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Fuel Efficiency", "Basic Safety"],
    image: MarutiSuzuki3,
    rating: 4.0,
    mileage: 35000,
    trending: false,
  },
  {
    id: 20,
    brand: "MarutiSuzuki",
    model: "Maruti-Dzire",
    category: "Sedan",
    year: 2021,
    price_per_day: 55,
    availability: true,
    location: "Hyderabad",
    transmission: "Manual",
    fuel_type: "Diesel",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Fuel Efficiency", "Bluetooth"],
    image: MarutiSuzuki4,
    rating: 4.3,
    mileage: 20000,
    trending: false,
  },
  {
    id: 21,
    brand: "MarutiSuzuki",
    model: "Maruti-Ertiga",
    category: "MPV",
    year: 2022,
    price_per_day: 60,
    availability: true,
    location: "Chennai",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seating_capacity: 7,
    air_conditioning: true,
    features: ["Rear Camera", "Bluetooth"],
    image: MarutiSuzuki5,
    rating: 4.5,
    mileage: 15000,
    trending: true,
  },
  {
    id: 22,
    brand: "MarutiSuzuki",
    model: "Maruti-Ciaz",
    category: "Sedan",
    year: 2021,
    price_per_day: 70,
    availability: true,
    location: "Pune",
    transmission: "Automatic",
    fuel_type: "Diesel",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Rear Camera", "Sunroof"],
    image: MarutiSuzuki6,
    rating: 4.6,
    mileage: 20000,
    trending: true,
  },
  {
    id: 23,
    brand: "MarutiSuzuki",
    model: "Maruti-Alto",
    category: "Hatchback",
    year: 2020,
    price_per_day: 35,
    availability: true,
    location: "Kolkata",
    transmission: "Manual",
    fuel_type: "Petrol",
    seating_capacity: 4,
    air_conditioning: false,
    features: ["Fuel Efficiency"],
    image: MarutiSuzuki7,
    rating: 4.0,
    mileage: 40000,
    trending: false,
  },
  {
    id: 24,
    brand: "MarutiSuzuki",
    model: "Maruti-Vitara Brezza",
    category: "SUV",
    year: 2022,
    price_per_day: 65,
    availability: true,
    location: "Jaipur",
    transmission: "Automatic",
    fuel_type: "Diesel",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Rear Camera", "Advanced Safety"],
    image: MarutiSuzuki8,
    rating: 4.6,
    mileage: 15000,
    trending: false,
  },
];

import Toyota1 from "./assets/images/cars/Toyota-1.png";
import Toyota2 from "./assets/images/cars/Toyota-2.png";
import Toyota3 from "./assets/images/cars/Toyota-3.png";
import Toyota4 from "./assets/images/cars/Toyota-4.png";
import Toyota5 from "./assets/images/cars/Toyota-5.png";
import Toyota6 from "./assets/images/cars/Toyota-6.png"; // Correct the duplicate import
import Toyota7 from "./assets/images/cars/Toyota-7.png";
import Toyota8 from "./assets/images/cars/Toyota-8.png";

export const Toyota = [
  {
    id: 25,
    brand: "Toyota",
    model: "Toyota-Corolla",
    category: "Sedan",
    year: 2022,
    price_per_day: 80,
    availability: true,
    location: "Mumbai",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Bluetooth", "Rear Camera", "Fuel Efficiency"],
    image: Toyota1, // Corrected the image reference
    rating: 4.7,
    mileage: 15000,
    trending: true,
  },
  {
    id: 26,
    brand: "Toyota",
    model: "Toyota-Camry",
    category: "Sedan",
    year: 2023,
    price_per_day: 110,
    availability: true,
    location: "Delhi",
    transmission: "Automatic",
    fuel_type: "Hybrid",
    seating_capacity: 5,
    air_conditioning: true,
    features: [
      "Panoramic Sunroof",
      "Advanced Safety Features",
      "Luxury Interior",
    ],
    image: Toyota2, // Corrected the image reference
    rating: 4.9,
    mileage: 8000,
    trending: false,
  },
  {
    id: 27,
    brand: "Toyota",
    model: "Toyota-Innova Crysta",
    category: "MPV",
    year: 2022,
    price_per_day: 85,
    availability: true,
    location: "Bangalore",
    transmission: "Manual",
    fuel_type: "Diesel",
    seating_capacity: 7,
    air_conditioning: true,
    features: ["Spacious Interior", "Rear Camera", "Bluetooth"],
    image: Toyota3, // Corrected the image reference
    rating: 4.6,
    mileage: 12000,
    trending: false,
  },
  {
    id: 28,
    brand: "Toyota",
    model: "Toyota-Fortuner",
    category: "SUV",
    year: 2023,
    price_per_day: 120,
    availability: true,
    location: "Chennai",
    transmission: "Automatic",
    fuel_type: "Diesel",
    seating_capacity: 7,
    air_conditioning: true,
    features: [
      "Off-Road Capability",
      "Luxury Interior",
      "Advanced Safety Features",
    ],
    image: Toyota4, // Corrected the image reference
    rating: 4.8,
    mileage: 9000,
    trending: false,
  },
  {
    id: 29,
    brand: "Toyota",
    model: "Toyota-Yaris",
    category: "Sedan",
    year: 2021,
    price_per_day: 60,
    availability: true,
    location: "Pune",
    transmission: "Manual",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Fuel Efficiency", "Rear Camera"],
    image: Toyota5, // Corrected the image reference
    rating: 4.4,
    mileage: 20000,
    trending: false,
  },
  {
    id: 30,
    brand: "Toyota",
    model: "Toyota-Urban Cruiser",
    category: "SUV",
    year: 2022,
    price_per_day: 70,
    availability: true,
    location: "Hyderabad",
    transmission: "Manual",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Bluetooth", "Compact Design", "Fuel Efficiency"],
    image: Toyota6, // Corrected the image reference
    rating: 4.5,
    mileage: 15000,
    trending: false,
  },
  {
    id: 31,
    brand: "Toyota",
    model: "Toyota-Highlander",
    category: "SUV",
    year: 2023,
    price_per_day: 100,
    availability: true,
    location: "Ahmedabad",
    transmission: "Automatic",
    fuel_type: "Hybrid",
    seating_capacity: 7,
    air_conditioning: true,
    features: ["Advanced Safety Features", "Spacious Interior", "Rear Camera"],
    image: Toyota7, // Corrected the image reference
    rating: 4.8,
    mileage: 10000,
    trending: false,
  },
  {
    id: 32,
    brand: "Toyota",
    model: "Toyota-Land Cruiser",
    category: "SUV",
    year: 2023,
    price_per_day: 150,
    availability: true,
    location: "Jaipur",
    transmission: "Automatic",
    fuel_type: "Diesel",
    seating_capacity: 7,
    air_conditioning: true,
    features: ["Luxury Features", "Off-Road Capability", "Panoramic Sunroof"],
    image: Toyota8, // Corrected the image reference
    rating: 4.9,
    mileage: 5000,
    trending: false,
  },
];

import Hyundai1 from "./assets/images/cars/Hyundai-1.png";
import Hyundai2 from "./assets/images/cars/Hyundai-2.png";
import Hyundai3 from "./assets/images/cars/Hyundai-3.png";
import Hyundai4 from "./assets/images/cars/Hyundai-4.png";
import Hyundai5 from "./assets/images/cars/Hyundai-5.png";
import Hyundai6 from "./assets/images/cars/Hyundai-6.png";
import Hyundai7 from "./assets/images/cars/Hyundai-7.png";
import Hyundai8 from "./assets/images/cars/Hyundai-8.png";

export const Hyundai = [
  {
    id: 33,
    brand: "Hyundai",
    model: "Hyundai-Elantra",
    category: "Sedan",
    year: 2022,
    price_per_day: 70,
    availability: true,
    location: "Mumbai",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Bluetooth", "Rear Camera", "LED Headlights"],
    image: Hyundai1,
    rating: 4.6,
    mileage: 18000,
    trending: true,
  },
  {
    id: 34,
    brand: "Hyundai",
    model: "Hyundai-Verna",
    category: "Sedan",
    year: 2023,
    price_per_day: 80,
    availability: true,
    location: "Delhi",
    transmission: "Manual",
    fuel_type: "Diesel",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Panoramic Sunroof", "Bluetooth", "Leather Upholstery"],
    image: Hyundai2,
    rating: 4.7,
    mileage: 12000,
    trending: false,
  },
  {
    id: 35,
    brand: "Hyundai",
    model: "Hyundai-Santro",
    category: "Hatchback",
    year: 2022,
    price_per_day: 50,
    availability: true,
    location: "Bangalore",
    transmission: "Manual",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Compact Design", "Fuel Efficiency", "Bluetooth"],
    image: Hyundai3,
    rating: 4.5,
    mileage: 25000,
    trending: false,
  },
  {
    id: 36,
    brand: "Hyundai",
    model: "Hyundai-Kona",
    category: "SUV",
    year: 2023,
    price_per_day: 100,
    availability: true,
    location: "Chennai",
    transmission: "Automatic",
    fuel_type: "Electric",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Electric Drive", "Sunroof", "Wireless Charging"],
    image: Hyundai4,
    rating: 4.8,
    mileage: 5000,
    trending: false,
  },
  {
    id: 37,
    brand: "Hyundai",
    model: "Hyundai-Creta",
    category: "SUV",
    year: 2022,
    price_per_day: 90,
    availability: true,
    location: "Hyderabad",
    transmission: "Automatic",
    fuel_type: "Diesel",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Rear Camera", "Bluetooth", "LED Headlights"],
    image: Hyundai5,
    rating: 4.7,
    mileage: 15000,
    trending: false,
  },
  {
    id: 38,
    brand: "Hyundai",
    model: "Hyundai-Tucson",
    category: "SUV",
    year: 2023,
    price_per_day: 110,
    availability: true,
    location: "Pune",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Panoramic Sunroof", "All-Wheel Drive", "Wireless Charging"],
    image: Hyundai6,
    rating: 4.9,
    mileage: 8000,
    trending: false,
  },
  {
    id: 39,
    brand: "Hyundai",
    model: "Hyundai-Ioniq",
    category: "Sedan",
    year: 2023,
    price_per_day: 120,
    availability: true,
    location: "Kolkata",
    transmission: "Automatic",
    fuel_type: "Hybrid",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Advanced Safety Features", "Bluetooth", "Wireless Charging"],
    image: Hyundai7,
    rating: 4.8,
    mileage: 6000,
    trending: false,
  },
  {
    id: 40,
    brand: "Hyundai",
    model: "Hyundai-Palisade",
    category: "SUV",
    year: 2023,
    price_per_day: 130,
    availability: true,
    location: "Ahmedabad",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seating_capacity: 7,
    air_conditioning: true,
    features: ["Luxury Interior", "Heated Seats", "Advanced Navigation System"],
    image: Hyundai8,
    rating: 4.9,
    mileage: 4000,
    trending: false,
  },
];

import MercedesBenz1 from "./assets/images/cars/Mercedes-Benz-1.png";
import MercedesBenz2 from "./assets/images/cars/Mercedes-Benz-2.png";
import MercedesBenz3 from "./assets/images/cars/Mercedes-Benz-3.png";
import MercedesBenz4 from "./assets/images/cars/Mercedes-Benz-4.png";
import MercedesBenz5 from "./assets/images/cars/Mercedes-Benz-5.png";
import MercedesBenz6 from "./assets/images/cars/Mercedes-Benz-6.png";
import MercedesBenz7 from "./assets/images/cars/Mercedes-Benz-7.png";
import MercedesBenz8 from "./assets/images/cars/Mercedes-Benz-8.png";

export const MercedesBenz = [
  {
    id: 41,
    brand: "MercedesBenz",
    model: "Mercedes-Benz-C-Class",
    category: "Sedan",
    year: 2023,
    price_per_day: 150,
    availability: true,
    location: "Mumbai",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Sunroof", "Leather Seats", "Bluetooth"],
    image: MercedesBenz1,
    rating: 4.8,
    mileage: 15000,
    trending: true,
  },
  {
    id: 42,
    brand: "MercedesBenz",
    model: "Mercedes-Benz-E-Class",
    category: "Sedan",
    year: 2022,
    price_per_day: 160,
    availability: true,
    location: "Delhi",
    transmission: "Automatic",
    fuel_type: "Diesel",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Adaptive Cruise Control", "Bluetooth", "360 Camera"],
    image: MercedesBenz2,
    rating: 4.9,
    mileage: 12000,
    trending: true,
  },
  {
    id: 43,
    brand: "MercedesBenz",
    model: "Mercedes-Benz-S-Class",
    category: "Luxury Sedan",
    year: 2023,
    price_per_day: 250,
    availability: true,
    location: "Bangalore",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: [
      "Massage Seats",
      "Burmester Sound System",
      "Heated & Ventilated Seats",
    ],
    image: MercedesBenz3,
    rating: 5.0,
    mileage: 8000,
    trending: false,
  },
  {
    id: 44,
    brand: "MercedesBenz",
    model: "Mercedes-Benz-GLA",
    category: "SUV",
    year: 2023,
    price_per_day: 180,
    availability: true,
    location: "Chennai",
    transmission: "Automatic",
    fuel_type: "Diesel",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Panoramic Sunroof", "Apple CarPlay", "Wireless Charging"],
    image: MercedesBenz4,
    rating: 4.7,
    mileage: 10000,
    trending: false,
  },
  {
    id: 45,
    brand: "MercedesBenz",
    model: "Mercedes-Benz-GLC",
    category: "SUV",
    year: 2023,
    price_per_day: 200,
    availability: true,
    location: "Hyderabad",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["LED Headlights", "Heated Seats", "Blind Spot Monitoring"],
    image: MercedesBenz5,
    rating: 4.8,
    mileage: 5000,
    trending: false,
  },
  {
    id: 46,
    brand: "MercedesBenz",
    model: "Mercedes-Benz-GLS",
    category: "Luxury SUV",
    year: 2023,
    price_per_day: 300,
    availability: true,
    location: "Pune",
    transmission: "Automatic",
    fuel_type: "Diesel",
    seating_capacity: 7,
    air_conditioning: true,
    features: ["Luxury Interior", "3D Surround Sound", "Adaptive Suspension"],
    image: MercedesBenz6,
    rating: 5.0,
    mileage: 4000,
    trending: false,
  },
  {
    id: 47,
    brand: "MercedesBenz",
    model: "Mercedes-Benz-A-Class",
    category: "Hatchback",
    year: 2023,
    price_per_day: 120,
    availability: true,
    location: "Kolkata",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["LED Lighting", "Active Parking Assist", "Apple CarPlay"],
    image: MercedesBenz7,
    rating: 4.6,
    mileage: 18000,
    trending: false,
  },
  {
    id: 48,
    brand: "MercedesBenz",
    model: "Mercedes-Benz-AMG-GT",
    category: "Sports Car",
    year: 2023,
    price_per_day: 400,
    availability: true,
    location: "Ahmedabad",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seating_capacity: 2,
    air_conditioning: true,
    features: [
      "Turbocharged Engine",
      "Luxury Interior",
      "High-Performance Wheels",
    ],
    image: MercedesBenz8,
    rating: 5.0,
    mileage: 3000,
    trending: false,
  },
];

export const carChooses = [
  {
    id: 1,
    brand: "BMW",
    model: "BMW-X5",
    category: "SUV",
    year: 2022,
    price_per_day: 120,
    availability: true,
    location: "New York",
    transmission: "Automatic",
    fuel_type: "Diesel",
    seating_capacity: 7,
    air_conditioning: true,
    features: ["Bluetooth", "GPS", "Sunroof"],
    image: BMW1,
    rating: 4.8,
    mileage: 15000,
    trending: true,
  },
  {
    id: 2,
    brand: "BMW",
    model: "BMW-3Series",
    category: "Sedan",
    year: 2021,
    price_per_day: 90,
    availability: true,
    location: "Los Angeles",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Heated Seats", "Sunroof"],
    image: BMW2,
    rating: 4.7,
    mileage: 20000,
    trending: false,
  },
  {
    id: 3,
    brand: "MercedesBenz",
    model: "Mercedes-Benz-S-Class",
    category: "Luxury Sedan",
    year: 2023,
    price_per_day: 250,
    availability: true,
    location: "Bangalore",
    transmission: "Automatic",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: [
      "Massage Seats",
      "Burmester Sound System",
      "Heated & Ventilated Seats",
    ],
    image: MercedesBenz3,
    rating: 5.0,
    mileage: 8000,
    trending: false,
  },
  {
    id: 4,
    brand: "MercedesBenz",
    model: "Mercedes-Benz-GLA",
    category: "SUV",
    year: 2023,
    price_per_day: 180,
    availability: true,
    location: "Chennai",
    transmission: "Automatic",
    fuel_type: "Diesel",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Panoramic Sunroof", "Apple CarPlay", "Wireless Charging"],
    image: MercedesBenz4,
    rating: 4.7,
    mileage: 10000,
    trending: false,
  },
  {
    id: 5,
    brand: "Mahindra",
    model: "Mahindra-Marazzo",
    category: "MPV",
    year: 2021,
    price_per_day: 70,
    availability: true,
    location: "Ahmedabad",
    transmission: "Manual",
    fuel_type: "Diesel",
    seating_capacity: 7,
    air_conditioning: true,
    features: ["Spacious Interior", "Bluetooth", "Rear Camera"],
    image: Mahindra5,
    rating: 4.4,
    mileage: 25000,
    trending: false,
  },
  {
    id: 6,
    brand: "Mahindra",
    model: "Mahindra-KUV100",
    category: "Compact SUV",
    year: 2020,
    price_per_day: 50,
    availability: true,
    location: "Chennai",
    transmission: "Manual",
    fuel_type: "Petrol",
    seating_capacity: 5,
    air_conditioning: true,
    features: ["Fuel Efficiency", "Basic Safety"],
    image: Mahindra6,
    rating: 4.2,
    mileage: 30000,
    trending: false,
  },
];

export const faqs = [
  {
    id: 1,
    question: "What documents are required to rent a car?",
    answer:
      "You need a valid driver's license, a government-issued photo ID, and a credit card to rent a car.",
  },
  {
    id: 2,
    question: "What is the minimum age to rent a car?",
    answer:
      "The minimum age is typically 21, but it may vary by location. Drivers under 25 may incur an additional young driver fee.",
  },
  {
    id: 3,
    question: "Can I rent a car with a debit card?",
    answer:
      "Yes, many rental companies accept debit cards, but additional verification or restrictions may apply.",
  },
  {
    id: 4,
    question: "Is there a mileage limit on the rental cars?",
    answer:
      "Some rentals offer unlimited mileage, while others may have restrictions. Check with the rental company for specific terms.",
  },
  {
    id: 5,
    question: "What happens if I return the car late?",
    answer:
      "Returning the car late may result in additional charges. Most companies offer a grace period but charge hourly or daily rates thereafter.",
  },
  {
    id: 6,
    question: "Are there additional fees for adding a second driver?",
    answer:
      "Yes, many companies charge a fee for adding a second driver. However, some rental agreements include a free additional driver.",
  },
  {
    id: 7,
    question: "What should I do if the car breaks down?",
    answer:
      "Contact the rental company's roadside assistance immediately. They will guide you through the process of repair or replacement.",
  },
  {
    id: 8,
    question: "Can I pick up a car in one city and drop it off in another?",
    answer:
      "Yes, one-way rentals are possible but may involve an additional fee. Confirm with the rental company for details.",
  },
  {
    id: 9,
    question: "Do I need to refill the fuel before returning the car?",
    answer:
      "Yes, most rental companies require you to return the car with a full tank of fuel, or they may charge a refueling fee.",
  },
  {
    id: 10,
    question: "Is insurance included in the rental price?",
    answer:
      "Basic insurance is often included, but additional coverage, like collision damage waiver (CDW), may be purchased separately.",
  },
];

import testimonial1 from "./assets/images/testimonial/testimonial-1.jpg";
import testimonial2 from "./assets/images/testimonial/testimonial-2.jpg";
import testimonial3 from "./assets/images/testimonial/testimonial-3.jpg";
import testimonial4 from "./assets/images/testimonial/testimonial-4.jpg";
import testimonial5 from "./assets/images/testimonial/testimonial-5.jpg";
import testimonial6 from "./assets/images/testimonial/testimonial-6.jpg";
import customer1 from "./assets/images/testimonial/customer-1.png";
import customer2 from "./assets/images/testimonial/customer-2.png";
import customer3 from "./assets/images/testimonial/customer-3.png";
import customer4 from "./assets/images/testimonial/customer-4.png";
import customer5 from "./assets/images/testimonial/customer-5.png";
import customer6 from "./assets/images/testimonial/customer-6.png";
export const testimonials = [
  {
    id: 1,
    name: "Sophia Carter",
    profile: customer1,
    backgroundImage: testimonial1,
    description:
      "Sophia appreciated the seamless booking process and the wide range of vehicles available. She highlighted how the friendly staff made her family road trip stress-free and enjoyable.",
  },
  {
    id: 2,
    name: "Michael Davis",
    profile: customer2,
    backgroundImage: testimonial2,
    description:
      "Michael commended the exceptional customer service and the pristine condition of the car he rented. He particularly liked the flexible pickup and drop-off options.",
  },
  {
    id: 3,
    name: "Emily Johnson",
    profile: customer3,
    backgroundImage: testimonial3,
    description:
      "Emily praised the affordability and reliability of the rental service. She mentioned how easy it was to find a car that fit her budget for her weekend getaway.",
  },
  {
    id: 4,
    name: "Jessica Brown",
    profile: customer4,
    backgroundImage: testimonial4,
    description:
      "Jessica loved the luxury vehicle options for a special event. She was impressed with the easy-to-navigate website and the quick confirmation of her booking.",
  },
  {
    id: 5,
    name: "Olivia Martinez",
    profile: customer5,
    backgroundImage: testimonial5,
    description:
      "Olivia found the rental process smooth and efficient. She appreciated the staff's helpful recommendations for navigating the city during her visit.",
  },
  {
    id: 6,
    name: "Liam Nguyen",
    profile: customer6,
    backgroundImage: testimonial6,
    description:
      "Liam highlighted the variety of eco-friendly cars available. He enjoyed the hassle-free return process and the excellent mileage of the hybrid he rented.",
  },
];
